import Header from "@/components/header";
import type { Metadata } from "next";
import Sidebar from "@/components/sidebar";
import { SidebarContextProvider } from "@/context/sidebar-context";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "CTS Database",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarContextProvider>
      <Header />
      <div className="flex">
        <Sidebar />
        {children}
      </div>
      <Footer />
    </SidebarContextProvider>
  );
}
