import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./../components/Sidebar";
import { BsArrowLeftShort } from "react-icons/bs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar />
          <div className="p-7">{children}</div>
        </div>
      </body>
    </html>
  );
}
