import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./../components/Sidebar";
import { BsArrowLeftShort } from "react-icons/bs";
import Header from "./../components/Header";
import Footer from "./../components/Footer";
import MenuContextProvider from "@/context/MenuContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-100 w-screen flex flex-col h-screen`}
      >
        <MenuContextProvider>
          <Header />
          <div className="flex h-full">
            <Sidebar />
            <main className="p-7">{children}</main>
          </div>
          <Footer />
        </MenuContextProvider>
      </body>
    </html>
  );
}
