import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import '../styles/global.css';

export const metadata: Metadata = {
  title: "CTS Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='dark:text-white dark:bg-neutral-800'>
        {children}
      </body>
    </html>
  );
}
