import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import '../styles/global.css';
import { MenuItemsContextProvider } from "@/context/menu-items-context";
import { ThemeContext, ThemeContextProvider } from "@/context/theme-context";

export const metadata: Metadata = {
  title: "CTS Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='dark:text-white dark:bg-neutral-800'>
        <ThemeContextProvider>
          <MenuItemsContextProvider>
          {children}
          </MenuItemsContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
